# Completion model

# Chat model
[model.chat.http]
kind = "openai/chat"
model_name = "qwen2.5-coder:7b-instruct-q4_0"
api_endpoint = "http://localhost:11434/v1"

# Embedding model
[model.embedding.http]
kind = "ollama/embedding"
model_name = "nomic-embed-text"
api_endpoint = "http://localhost:11434"
