################################################################################
#                                                                              #
#           https://github.com/leukipp/cortile/blob/main/config.toml           #
#                                                                              #
################################################################################

#################################### Tiling ####################################

# Initial tiling activation, will be cached afterwards (true | false).
tiling_enabled = false

# Initial tiling layout, will be cached afterwards ("vertical-left" | "vertical-right" | "horizontal-top" | "horizontal-bottom" | "maximized" | "fullscreen").
tiling_layout = "vertical-right"

# An overlay window is displayed for this time period [ms] when the layout was changed (0 = disabled).
tiling_gui = 1000

# Menu entries in systray which shows the tiling state as icon ([] = disabled).
# tiling_icon = [
#   ["ACTION", "TEXT"] = ["action strings from [keys] section", "text to show in the menu"],
#   ["", ""] = "show a separator line",
# ]
tiling_icon = [
    ["toggle", "Enabled"],
    ["", ""],
    ["master_increase", "Add Master"],
    ["master_decrease", "Remove Master"],
    ["", ""],
    ["slave_increase", "Add Slave"],
    ["slave_decrease", "Remove Slave"],
    ["", ""],
    ["reset", "Reset"],
    ["exit", "Exit"],
]

#################################### Window ####################################

# Regex RE2 syntax to ignore windows (WM_CLASS string can be found by running `xprop WM_CLASS`).
# window_ignore = [
#   ["WM_CLASS", "WM_NAME"] = ["ignore all windows with this class", "but allow those with this name"]
# ]
window_ignore = [
    ["nm.*", ""],
    ["gcr.*", ""],
    ["polkit.*", ""],
    ["wrapper.*", ""],
    ["lightdm.*", ""],
    ["blueman.*", ""],
    ["pavucontrol.*", ""],
    ["firefox.*", ".*Mozilla Firefox"],
]

# Maximum number of allowed master windows (0 - 5).
window_masters_max = 2

# Maximum number of allowed slave windows (1 - 5).
window_slaves_max = 4

# How much space should be left between windows (0 - 100).
window_gap_size = 0

# Initial rendering of window decorations, will be cached afterwards (true | false).
window_decoration = true

################################## Proportion ##################################

# How much to increment/decrement master-slave area (0.0 - 1.0).
proportion_step = 0.05

# Minimum window width/height in proportion to workspace (0.0 - 1.0).
proportion_min = 0.2

##################################### Edge #####################################

# Margin of the tiling area ([top, right, bottom, left]).
edge_margin = [0, 0, 0, 0]

# Margin of the tiling area on primary screen ([top, right, bottom, left]).
edge_margin_primary = [0, 0, 0, 0]

# Width and height of a hot-corner area within the edge corners (0 - 100).
edge_corner_size = 10

# Width or height of a hot-corner area within the edge centers (0 - 100).
edge_center_size = 100

################################################################################
[colors]                             # RGBA color values used for ui elements. #
################################################################################

# Window text color.
gui_text = [160, 156, 252, 255]

# Window background color.
gui_background = [255, 255, 255, 255]

# Slave client layout color.
gui_client_slave = [160, 156, 252, 255]

# Master client layout color.
gui_client_master = [160, 156, 252, 255]

# Systray icon background color.
icon_background = [0, 0, 0, 0]

# Systray icon foreground color.
icon_foreground = [0, 0, 0, 255]

################################################################################
[keys]                            # Key symbols can be found by running `xev`. #
################################################################################

# Enable tiling on the current screen (Home = Fn_Left).
enable = "Control-Mod4-T"

# disable = "Control-Shift-End"
# toggle = "Control-Mod4-T"


# Disable tiling and restore windows on the current screen.
restore = "Control-Mod4-R"
cycle_next = "Shift-Mod4-1"
cycle_previous = "Control-Mod4-1"
master_make = "Mod4-1"
master_increase = "Control-Mod4-3"
master_decrease = "Control-Mod4-2"
slave_increase = "Shift-Mod4-3"
slave_decrease = "Shift-Mod4-2"
proportion_increase = "Mod4-3"
proportion_decrease = "Mod4-2"

################################################################################
[corners]                                # Action strings from [keys] section. #
################################################################################

top_left = ""
top_center = ""
top_right = ""
center_right = ""
bottom_right = ""
bottom_center = ""
bottom_left = ""
center_left = ""

################################################################################
[systray]                                # Action strings from [keys] section. #
################################################################################

click_left = ""
click_middle = "toggle"
click_right = ""
scroll_up = "cycle_previous"
scroll_down = "cycle_next"
scroll_left = "proportion_decrease"
scroll_right = "proportion_increase"
