#!/bin/bash
basedir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
username="user"

while getopts u:a:f: flag
do
    case "${flag}" in
        u) username=${OPTARG};;
    esac
done

echo "working dir: $basedir"

sh $basedir/user
sh $basedir/sudo
sh $basedir/slackpkg
sh $basedir/slpkg
sh $basedir/multilib

echo "============== [ setup done ] ==============="
echo "username: $username"
echo "it's recommended to reboot your system."
echo "upon reboot you can sign in with your new user"
echo "=============================================="

read -p "press enter to return to shell"
