#!/bin/bash
basedir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cp $basedir/post-functions.conf /etc/slackpkg/post-functions.conf

if [[ -f "$HOME/.step1-done" ]]; then
  sh $basedir/step2
  exit
fi

if [[ ! -f "$HOME/.stable-done" ]]; then
  sh $basedir/update-stable
fi

if [[ ! -f "$HOME/.current-done" ]]; then
  sh $basedir/update-current
fi

if [[ ! -f "$HOME/.purge-done" ]]; then
  sh $basedir/package-purge
fi

rm /etc/slackpkg/post-functions.conf

echo "sh $basedir/step2" >> /root/.bash_profile
touch ~/.step1-done

echo "=================== [ system reboot ] =================="
printf "\x1b[1;31mREAD CAREFULLY:\033[0m\n"
echo "your system will now reboot, after reboot make sure to"
printf "SIGN IN \x1b[1;31mAS ROOT\x1b[0m !!!\n"
echo "========================================================"
read -p "press enter to reboot"
reboot

