#!/bin/bash
basedir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

kernelver="6.15.2"

sh $basedir/slpkg
sh $basedir/multilib

echo "============== [ kernel update ] ==============="
echo "you can choose to update your kernel"
echo "after system reboot."
echo "this will update your kernel to $kernelver"
echo "================================================"

nreboot=0

read -p "do you want to update your kernel [y/n]? (y):" choice
if [[ $choice == "y" ]]; then
  nreboot=1
  sh $basedir/kernel
fi

echo "================= [ nvidia driver ] ================="
echo "you can choose to install the nvidia driver"
echo "after system reboot."
echo "this will install the nvidia kernel module and the"
echo "gpu driver."
echo "====================================================="

read -p "do you want to install the nvidia driver [y/n]? (y):" choice
if [[ $choice == "y" ]]; then
  nreboot=1
  sh $basedir/nvidia
fi

if [[ $nreboot == 1 ]]; then
  echo "sh $basedir/finish" >> /root/.bash_profile
  echo "rm -f /root/.bashrc" >> /root/.bash_profile
  echo "============================ [ reboot ] ==========================="
  printf "\x1b[1;31mupon reboot, make sure to log in as ROOT first !!!\x1b[0;0m\n"
  echo "==================================================================="
  read -p "press enter to reboot your system"
  echo "rebooting..."
  reboot
else
  sh $basedir/runlevel

  echo "============== [ setup done ] ==============="
  echo "username: $username"
  echo "you may now log into your user account."
  echo "it is recommended to reboot your system now."
  echo "=============================================="
fi
